name: Docker Release

on:
    push:
        branches: [master, main]
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - run: npm i
            - name: Print GitHub ref
              run: echo "GITHUB_REF=${GITHUB_REF}"
            # - name: Get latest Git tag
            #   id: tag
            #   run: |
            #       git fetch --tags
            #       TAG=$(git describe --tags --abbrev=0)
            #       echo "tag=$TAG" >> $GITHUB_OUTPUT
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/${{ github.repository_owner }}/stencil-cli
                  context: git
                  tags: |
                    type=semver,pattern={{version}}
                    type=semver,pattern={{major}},prefix=
            # - name: Set up Docker Buildx
            #   uses: docker/setup-buildx-action@v3

            # - name: Build and push
            #   uses: docker/build-push-action@v6
            #   with:
            #       push: true
            #       tags: ${{ steps.meta.outputs.tags }}
